apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-portfolio-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/cks8483/app-repo.git'
    targetRevision: HEAD
    path: k8s # Manifest 파일들이 위치한 경로
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-portfolio # 앱이 배포될 네임스페이스
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true