apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-web
  template:
    metadata:
      labels:
        app: image-web
    spec:
      containers:
      - name: web
        image: chan8483/image-service:v1  # [변경] ID 적용
        # command: ... (삭제함, Dockerfile의 CMD 사용)
        ports:
        - containerPort: 5000
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: MINIO_ENDPOINT
          value: "http://minio:9000"