apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-web.yaml
- deployment-worker.yaml
- service.yaml
images:
- name: chan8483/image-service
  newName: chan8483/image-service
  newTag: dc62772
