apiVersion: v1
kind: Service
metadata:
  name: image-web-svc
spec:
  type: LoadBalancer
  selector:
    app: image-web  # image-web Deployment만 바라봄 (워커는 포트 노출 필요 없음)
  ports:
  - port: 80
    targetPort: 5000