name: CI/CD for Mono Repo

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'requirements.txt'
      - 'k8s/**'
  workflow_dispatch:

env:
  IMAGE_NAME: chan8483/myapp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & Push Docker Hub
      - name: Build and Push Docker Image
        id: build-image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ env.IMAGE_NAME }}:${IMAGE_TAG} .
          docker push ${{ env.IMAGE_NAME }}:${IMAGE_TAG}
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      # Update Kustomize Image
      - name: Update Image Tag in Kustomization
        run: |
          cd k8s/base
          kustomize edit set image ${{ env.IMAGE_NAME }}=${{ env.IMAGE_NAME }}:${{ steps.build-image.outputs.IMAGE_TAG }}

      # Commit & Push
      - name: Commit and Push Manifest Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions-bot@github.com"
          git add k8s/base/kustomization.yaml
          git diff --quiet && git diff --staged --quiet || git commit -m "CI: Update image tag to ${{ steps.build-image.outputs.IMAGE_TAG }}"
          git push
